name: fibre-framework # you probably want to 'snapcraft register <name>'
version: '1.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Event Driven | Web Server | NodeJS | Framework
description:
  Start building blazing fast web applications and API services with Fibre Framework,
  built on top of NodeJS event driven single threaded architecture that can handle
  thousands of clients simultaneously with ease.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  fibre:
    source: .
    plugin: nodejs
    node-packages: [fs-extra]

apps:
  node-service:
    command: bin/fibre-framework
    plugs: [network-bind]