name: fibre-framework
version: '1.1.1'
summary: Event Driven | Web Server | NodeJS | Framework
description: |
  Start building blazing fast web applications and API services with Fibre Framework,
  built on top of NodeJS event driven single threaded architecture that can handle
  thousands of clients simultaneously with ease.

grade: stable
confinement: strict

parts:
  fibre:
    source: https://github.com/Fibre-Framework/fibre.git
    plugin: nodejs
    node-packages: [fs-extra]
    install: |
      mkdir -p /etc/fibre-framework/
      mkdir -p /etc/fibre-framework/config/
      snapdir=$(pwd)
      cp -n "$snapdir/config/server.json" /etc/fibre-framework/config/server.json

apps:
  node-service:
    command: bin/fibre-framework
    plugs: [network-bind]