#!/bin/sh
set -e

echo "Writing server.json file if it does not exist."
echo "sleep_time 5" > "$SNAP_DATA/server.json"

cat > "$SNAP_DATA/server.json" << EOL
{
    "websites": {
        "default": {
            "name": "My default website",
            "website_root": "my-website/",
            "document_root": "my-website/public/",
            "default_document": [".html"],
            "network": {
                "bind_address": "0.0.0.0"
            },
            "http": {
                "port": 80,
                "enabled": true
            },
            "https": {
                "port": 443,
                "certificate_path": "/certs/",
                "enabled": false
            },
            "extensions": {

            },
            "server_status": {
                "enabled": false,
                "route": "/server-status",
                "security": {
                    "allow_all": false,
                    "ip_address_block": "10.0.0.0/8"
                }
            },
            "default_headers": [
                {
                    "name": "X-Frame-Options",
                    "value": "deny",
                    "enabled": true
                },
                {
                    "name": "X-XSS-Protection",
                    "value": "1; mode=block",
                    "enabled": true
                },
                {
                    "name": "X-Content-Type-Options",
                    "value": "nosniff",
                    "enabled": true
                }
            ]
        }
    }
}
EOL

echo "Create the sites folder..."
mkdir -p "$SNAP_DATA/sites/"